import React from 'react';
import './LiteratureReview.css';

const SECTION_COLORS = {
  'Introduction':               '#00d4ff',
  'Summary of Existing Research': '#7c3aed',
  'Common Findings':            '#00ff88',
  'Differences Between Studies':'#ffaa00',
  'Research Gaps':              '#ff4d6d',
  'Conclusion':                 '#e879f9',
};

function parseSections(text) {
  if (!text) return [];

  // Match **N. Title** or **Title** patterns
  const sectionRegex = /\*\*(?:\d+\.\s*)?(.*?)\*\*/g;
  const sections = [];
  let lastIndex = 0;
  let lastTitle = null;

  let match;
  while ((match = sectionRegex.exec(text)) !== null) {
    if (lastTitle !== null) {
      sections.push({
        title: lastTitle,
        content: text.slice(lastIndex, match.index).trim(),
      });
    }
    lastTitle = match[1].trim();
    lastIndex = match.index + match[0].length;
  }

  // Push the last section
  if (lastTitle !== null) {
    sections.push({
      title: lastTitle,
      content: text.slice(lastIndex).trim(),
    });
  }

  // If no ** patterns found, return raw text as one block
  if (sections.length === 0) {
    return [{ title: null, content: text.trim() }];
  }

  return sections;
}

function getColor(title) {
  for (const [key, color] of Object.entries(SECTION_COLORS)) {
    if (title && title.toLowerCase().includes(key.toLowerCase())) return color;
  }
  // Cycle through colors for unknown sections
  const colors = Object.values(SECTION_COLORS);
  return colors[Math.floor(Math.random() * colors.length)];
}

export default function LiteratureReview({ review }) {
  if (!review) return null;
  const sections = parseSections(review);

  return (
    <section className="lit-section">
      <div className="section-label">Generated by AI</div>
      <h2 className="section-title">Literature Review</h2>
      <p className="section-desc">
        A comprehensive academic literature review synthesized from all uploaded papers.
      </p>

      <div className="lit-card glass-card">
        {sections.map((sec, i) => {
          const color = sec.title ? getColor(sec.title) : 'var(--accent-primary)';
          return (
            <div key={i} className="lit-block">
              {sec.title && (
                <div className="lit-heading-row">
                  <div className="lit-dot" style={{ background: color, boxShadow: `0 0 8px ${color}` }} />
                  <h3 className="lit-heading" style={{ color }}>{sec.title}</h3>
                </div>
              )}
              <p className="lit-text" style={{ borderLeftColor: `${color}40` }}>
                {sec.content}
              </p>
            </div>
          );
        })}
      </div>
    </section>
  );
}